Revert "writeprotect: delete unused chips/drivers"
This reverts commit f5089dd22967b243281a994fe10dd74e3408c97b.

Reason for revert: apparently this removed chips that are in use:

Found on kasumi DUT:

Found Winbond flash chip "W25Q128.W" (16384 kB, SPI) mapped at physical address 0x00000000ff000000.
Error: write protect is not supported on this flash chip.

Original change's description:
> writeprotect: delete unused chips/drivers
>
> More flashes can be deleted: b/209702833#comment3.
>
> BUG=b:182223106,b:209702833
> BRANCH=none
> TEST=builds
>
> Signed-off-by: Nikolai Artemiev <nartemiev@google.com>
> Change-Id: I6dda18e409dc97ce61a88f48ad666222d6c0dfa1
> Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/3346978
> Reviewed-by: Edward O'Callaghan <quasisec@chromium.org>
> Commit-Queue: Edward O'Callaghan <quasisec@chromium.org>

Bug: b:182223106,b:209702833,b:215453503
Change-Id: I6c025f56b7814e19763b7de1cd89918a1cded8bc
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/3403428
Tested-by: Nikolai Artemiev <nartemiev@google.com>
Auto-Submit: Nikolai Artemiev <nartemiev@google.com>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Reviewed-by: Edward O'Callaghan <quasisec@chromium.org>
Commit-Queue: Nikolai Artemiev <nartemiev@google.com>