BACKPORT: dummyflasher.c: Fix null par data and size param handling
This patch fixes a few bugs that two patches ( `3149822cd45cb2e5841e15d648783748ba1b2ec6` && `3b8fe0f8e907c0ba9f7c7935e950f3e1538d427f`) brought:
 * Check the presence of 'size' param only if the emulate is VARIABLE_SIZE.
 * Initialize 'flash->st->par.data' in dummy_init() so that it can probe the VARIABLE_SIZE emulator correct in probe_variable_size().
 * Replace atoi() with strtol().
 * Revise man page to describe how to use the VARIABLE_SIZE emulation target.

BUG=none
BRANCH=none
TEST=`
$ flashrom -p dummy:image=dummy.bin,emulate=VARIABLE_SIZE,size=16777216 \
-w ${IMG} -V -f
...
Verifying flash... VERIFIED.
Writing dummy.bin

$ flashrom -p dummy:image=dummy.bin,emulate=VARIABLE_SIZE -w ${IMG} -V -f
...
dummy_init: the size parameter is not given.
Unhandled programmer parameters (possibly due to another failure): image=dummy.bin,
Error: Programmer initialization failed

$ flashrom -p dummy:image=dummy.bin,emulate=SST25VF040.REMS -c SST25LF040A -w ${IMG}
...
Erasing and writing flash chip... Erase/write done.
Verifying flash... VERIFIED.

$ man flashrom
...
 * Dummy vendor VARIABLE_SIZE SPI flash chip (configurable size, page write)

 Example: flashrom -p dummy:emulate=SST25VF040.REMS

 To use VARIABLE_SIZE chip, size must be specified to configure the size of the flash chip as a power of two.

 Example: flashrom -p dummy:emulate=VARIABLE_SIZE,size=16777216,image=dummy.bin
...
`

Original-Signed-off-by: Namyoon Woo <namyoon@google.com>
Original-Change-Id: Ie6481943a831b946a91b643b4d79e684c27e48b8
Original-Reviewed-on: https://review.coreboot.org/c/flashrom/+/46536
Original-Tested-by: build bot (Jenkins) <no-reply@coreboot.org>
Original-Reviewed-by: Edward O'Callaghan <quasisec@chromium.org>
(cherry picked from commit f7a08a8ef22fa1e5bbbbbe10d39b7cf46bd5cb6c)

Change-Id: Id0610b13d1bfaf6f7f5ee9dd2883b7d3931468e1
Signed-off-by: Edward O'Callaghan <quasisec@google.com>
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/third_party/flashrom/+/2554159
Commit-Queue: Edward O'Callaghan <quasisec@chromium.org>
Tested-by: Edward O'Callaghan <quasisec@chromium.org>
Reviewed-by: Namyoon Woo <namyoon@chromium.org>
Reviewed-by: Sam McNally <sammc@chromium.org>
Auto-Submit: Edward O'Callaghan <quasisec@chromium.org>